name: Deploy Note Create Lambda

on:
  push:
    paths:
      - 'lambdas/note-create/**'
      - 'shared/**'
      - '.github/workflows/deploy-note-create.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install prod dependencies (in root)
        run: |
          rm -rf node_modules package-lock.json
          npm install --omit=dev

      - name: Build note-create Lambda
        run: npm run build:note-create

      - name: Install mongodb (external) into dist
        run: |
          cd lambdas/note-create/dist
          npm init -y
          npm install mongodb --omit=dev

      - name: List dist contents
        run: |
          cd lambdas/note-create/dist
          ls -l
          ls -l node_modules
          ls -l node_modules/mongodb || echo "NO MONGODB"


      - name: Zip Lambda bundle
        run: |
          cd lambdas/note-create/dist
          zip -r ../function.zip .

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}
        run: |
          aws lambda update-function-code \
            --function-name note-create \
            --zip-file fileb://lambdas/note-create/function.zip \
            --region $AWS_REGION

